### ISSUE TITLE
Method [honeypot] does not exist.

### ISSUE THREAD

**Issue by Rimman2000** [ianlandsman/Honeypot#5]
hello 
really need your help ... Honeypot work great on localhost but I upload to server it giving me error

http://www.shiateachings.com/public/ilm/article/20/3

when i remove this line of code from the page it works fine
" {{ Form::honeypot('honey_field_name', 'time_field_name') }} "

this is whole form

{{ Form::open('comments', 'POST', array('class' => 'adminf')) }}
name, email, text box field
{{ Form::submit('Post Comments') }}
{{ Form::honeypot('honey_field_name', 'time_field_name') }}
{{ Form::token() }}
{{ Form::close() }}

Unhandled Exception

Message:

Method [honeypot] does not exist.

Location:

/home/mirlabs/public_html/shiateachings/laravel/form.php on line 615
Stack Trace:
#0 /home/mirlabs/public_html/shiateachings/laravel/view.php(366) : eval()'d code(179): Laravel\Form::__callStatic('honeypot', Array)
#1 /home/mirlabs/public_html/shiateachings/laravel/view.php(366) : eval()'d code(179): Laravel\Form::honeypot('honey_field_nam...', 'time_field_name')
#2 /home/mirlabs/public_html/shiateachings/laravel/view.php(366): eval()
#3 /home/mirlabs/public_html/shiateachings/laravel/blade.php(71): Laravel\View->get()
#4 [internal function]: Laravel{closure}(Object(Laravel\View))
#5 /home/mirlabs/public_html/shiateachings/laravel/event.php(199): call_user_func_array(Object(Closure), Array)
#6 /home/mirlabs/public_html/shiateachings/laravel/event.php(138): Laravel\Event::fire('laravel.view.en...', Array, true)
#7 /home/mirlabs/public_html/shiateachings/laravel/view.php(337): Laravel\Event::until('laravel.view.en...', Array)
#8 /home/mirlabs/public_html/shiateachings/laravel/view.php(570): Laravel\View->render()
#9 /home/mirlabs/public_html/shiateachings/laravel/response.php(246): Laravel\View->__toString()
#10 /home/mirlabs/public_html/shiateachings/laravel/laravel.php(178): Laravel\Response->render()
#11 /home/mirlabs/public_html/shiateachings/public/index.php(34): require('/home/mirlabs/p...')
#12 {main}

Thank You..

**Comment by cboisen** [comment]
I have the same problem.. Did you find any solutions?
